name: pscdeakte-stack

x-healthcheck: &healthcheck
  interval: 30s
  timeout: 60s
  retries: 3
  start_period: 60s

x-security-settings: &security_settings
  security_opt:
    - no-new-privileges:true

services:
  postgres:
    image: postgres:17.7-alpine3.21@sha256:5bcb5623bb6999b2f7fbd2109f0bfc1f144d138b52ca35ede95d644d93585c2f
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    healthcheck:
      <<: *healthcheck
      test: ["CMD-SHELL", "pg_isready -d postgres -U admin"]
    <<: *security_settings

  pg-admin:
    image: dpage/pgadmin4:9.18.0@sha256:c332c5f6dfba995d9ebc4af261d93506d6876085d712eaaa3defc8dd1a3f26de
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
      - PGADMIN_REPLACE_SERVERS_ON_STARTUP=True
      - PGADMIN_DISABLE_POSTFIX=True
      - PGADMIN_LISTEN_PORT=5050
      - PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED=False
    ports:
      - "5050:5050"
    depends_on:
      - postgres
    healthcheck:
      <<: *healthcheck
      test: ["CMD", "wget", "-O", "-", "http://localhost:5050/misc/ping"]
    <<: *security_settings
    volumes:
      - './pgadmin/servers.json:/pgadmin4/servers.json:ro'
      - './pgadmin/preferences.json:/pgadmin4/preferences.json:ro'
      - './pgadmin/pgpass:/tmp/pgpass.mounted:ro'
      - './pgadmin/data:/tmp/data'
    entrypoint: >
      /bin/sh -c "
        cp -f /tmp/pgpass.mounted /tmp/pgpass;
        chmod 600 /tmp/pgpass;
        /entrypoint.sh
      "
  wiremock:
    image: wiremock/wiremock:3.13.2@sha256:0d4ecb3e4dc8213fd7a4d37d6a78f6e6b553a6d2e15bd51b0999781282ac61b3
    container_name: wiremock
    ports:
      - "8080:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/openapi:/home/wiremock/openapi
    command:
      - "--global-response-templating"
      - "--verbose"

  # === S3 ===
  rustfs:
    image: rustfs/rustfs:1.0.0
    environment:
      RUSTFS_ACCESS_KEY: admin
      RUSTFS_SECRET_KEY: admin
    ports:
      - "9000:9000" # API
      - "9001:9001" # UI
    volumes:
      - rustfs-data:/data
    healthcheck:
      <<: *healthcheck
      test: ["CMD", "curl", "-fsS", "http://localhost:9000/health/ready"]
    <<: *security_settings

  init-rustfs:
    image: rustfs/rc:v0.1.36
    depends_on:
      rustfs:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
        set -e;
        rc alias set local http://rustfs:9000 admin admin;
        rc mb local/test-bucket;
      "
    <<: *security_settings

volumes:
  rustfs-data:

networks:
  keycloak:
  internal:
